---
# tasks file for spotify


- name: Add the Spotify repository gpg signing keys
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    state: present
  register: spotify_add_key

#- name: debug
#  debug: var=spotify_add_key

- name: "Add the Spotify repository"
  apt_repository:
    repo: "deb http://repository.spotify.com stable non-free"
    filename: "spotify"
    state: present
    update_cache: "yes"

- name: install spotify
  package:
    name: "{{ spotify_packages }}"
    state: present
  register: spotify_install_spotify
  until: spotify_install_spotify is succeeded
  retries: 3

#- name: configure spotify
#  template:
#    src: "{{ spotify_config_file }}.j2"
#    dest: "{{ spotify_config_directory }}/{{ spotify_config_file }}"
#  notify:
#    - restart spotify

